language: php

php:
  - 8.0

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 8.0
      dist: focal
      env: setup=lowest
    - php: 8.2
      dist: focal

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - sudo apt-get update
  - sudo apt-get install libonig5
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script: vendor/bin/phpunit